### ISSUE TITLE
Is there a choose-your-own-adventure going from .pm to package?

### ISSUE THREAD

**Issue by LadyAleena** [rjbs/dzil.org#32]
I was wondering if there a choose-your-own-adventure going from free-floating .pm to package.

**Comment by rjbs** [comment]
I realize it's been a while, but in case you still have this question:  could you elaborate on it?  I'm not sure what you're asking.

**Comment by LadyAleena** [comment]
I am closing this issue as I have given up on trying to package modules for publication on CPAN. It is just too confusing.
